import type { Room, Restaurant, Destination, Testimonial, GalleryItem, NavItem } from "@/types";

export const NAV_ITEMS: NavItem[] = [
  {
    label: "Destinations",
    href: "#destinations",
    children: [
      { label: "Udaipur", href: "#destinations" },
      { label: "Jaipur", href: "#destinations" },
      { label: "Goa", href: "#destinations" },
      { label: "Mumbai", href: "#destinations" },
      { label: "Maldives", href: "#destinations" },
      { label: "Dubai", href: "#destinations" },
    ],
  },
  {
    label: "Hotels",
    href: "#hotels",
    children: [
      { label: "Palace Hotels", href: "#hotels" },
      { label: "Beach Resorts", href: "#hotels" },
      { label: "Mountain Retreats", href: "#hotels" },
      { label: "Urban Luxury", href: "#hotels" },
      { label: "Heritage Properties", href: "#hotels" },
    ],
  },
  {
    label: "Dining",
    href: "#dining",
    children: [
      { label: "Fine Dining", href: "#dining" },
      { label: "Rooftop Lounge", href: "#dining" },
      { label: "Royal Indian", href: "#dining" },
      { label: "International", href: "#dining" },
    ],
  },
  {
    label: "Experiences",
    href: "#experiences",
    children: [
      { label: "Spa & Wellness", href: "#wellness" },
      { label: "Weddings", href: "#weddings" },
      { label: "Royal Tours", href: "#experiences" },
      { label: "Private Events", href: "#experiences" },
    ],
  },
  { label: "Offers", href: "#offers", children: [] },
  { label: "Membership", href: "#membership", children: [] },
];

export const DESTINATIONS: Destination[] = [
  { name: "Udaipur", country: "India", tagline: "City of Lakes & Palaces", image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=900&q=85", properties: 3, tag: "Heritage" },
  { name: "Jaipur", country: "India", tagline: "The Pink City of Royals", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=900&q=85", properties: 2, tag: "Royal" },
  { name: "Goa", country: "India", tagline: "Sun, Sea & Serenity", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=900&q=85", properties: 4, tag: "Coastal" },
  { name: "Maldives", country: "Maldives", tagline: "Paradise on Earth", image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=900&q=85", properties: 2, tag: "Island" },
  { name: "Dubai", country: "UAE", tagline: "Where Opulence Lives", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&q=85", properties: 3, tag: "Urban" },
  { name: "London", country: "UK", tagline: "Timeless British Elegance", image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=900&q=85", properties: 2, tag: "Classic" },
  { name: "Paris", country: "France", tagline: "The Art of Living Well", image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=900&q=85", properties: 1, tag: "Iconic" },
  { name: "New York", country: "USA", tagline: "Luxury in the City of Dreams", image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=900&q=85", properties: 2, tag: "Metropolitan" },
];

export const ROOMS: Room[] = [
  {
    id: "presidential",
    name: "Presidential Suite",
    category: "Signature Collection",
    price: 185000,
    size: "320 sq m",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=85",
    imageNight: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200&q=85",
    description: "The pinnacle of luxury — a private palace within a palace, with panoramic views of Lake Pichola and a dedicated butler team available around the clock.",
    amenities: ["Private Pool", "Butler Service", "Rolls Royce Transfer", "Michelin Dining", "Helipad Access"],
    badge: "Most Exclusive",
    featured: true,
  },
  {
    id: "maharaja",
    name: "Royal Maharaja Suite",
    category: "Heritage Collection",
    price: 120000,
    size: "240 sq m",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=85",
    imageNight: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200&q=85",
    description: "Inspired by Rajput royalty, adorned with hand-painted frescoes, antique furnishings, and a private courtyard overlooking the palace gardens.",
    amenities: ["Heritage Décor", "Private Terrace", "Ayurvedic Spa", "Royal Dining"],
    badge: "Heritage",
  },
  {
    id: "ocean-villa",
    name: "Ocean Villa",
    category: "Villa Collection",
    price: 95000,
    size: "180 sq m",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=85",
    imageNight: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=85",
    description: "A private lakeside villa with your own infinity pool, personal chef, and unobstructed sunset views over the shimmering waters.",
    amenities: ["Private Pool", "Lake View", "Personal Chef", "Boat Access"],
    badge: "Lakeside",
  },
  {
    id: "sky-penthouse",
    name: "Sky Penthouse",
    category: "Penthouse Collection",
    price: 150000,
    size: "280 sq m",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=85",
    imageNight: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=85",
    description: "Perched atop the palace, offering 360° panoramic views of the city, lake, and Aravalli mountains with a private rooftop terrace.",
    amenities: ["360° Views", "Rooftop Terrace", "Home Theatre", "Helipad Access"],
    badge: "Sky Collection",
  },
  {
    id: "heritage-room",
    name: "Heritage Palace Room",
    category: "Classic Collection",
    price: 45000,
    size: "80 sq m",
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&q=85",
    imageNight: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&q=85",
    description: "Classic palace elegance with original 19th-century architecture, hand-carved furniture, and every modern luxury amenity.",
    amenities: ["Palace View", "Antique Décor", "Spa Access", "Concierge"],
    badge: "Classic",
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: "golden-ember",
    name: "Golden Ember",
    cuisine: "Modern Indian · Michelin ★★",
    description: "A theatrical dining experience where ancient Indian spices meet contemporary French technique. Chef Arjun Kapoor's 12-course tasting menu is a journey through India's culinary heritage.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=85",
    hours: "7:00 PM – 11:30 PM",
    location: "Ground Floor, East Wing",
    priceRange: "₹8,500 per person",
    tag: "Signature Restaurant",
    chef: "Chef Arjun Kapoor",
    chefImage: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=300&q=85",
  },
  {
    id: "sapphire-lounge",
    name: "The Sapphire Lounge",
    cuisine: "International · Cocktail Bar",
    description: "An intimate art-deco lounge serving rare single malts, bespoke cocktails, and light European bites. The perfect setting for pre-dinner aperitifs or late-night conversations.",
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=1200&q=85",
    hours: "5:00 PM – 2:00 AM",
    location: "Mezzanine Level",
    priceRange: "₹3,500 per person",
    tag: "Cocktail Lounge",
    chef: "Mixologist Priya Sharma",
    chefImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&q=85",
  },
  {
    id: "maharaja-courtyard",
    name: "Maharaja Courtyard",
    cuisine: "Royal Rajasthani · Heritage",
    description: "Dine under the stars in our 16th-century courtyard, surrounded by hand-carved marble pillars. Traditional Rajasthani thalis served with live folk music and cultural performances.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=85",
    hours: "12:00 PM – 3:30 PM · 7:30 PM – 11:00 PM",
    location: "Heritage Courtyard",
    priceRange: "₹5,500 per person",
    tag: "Heritage Dining",
    chef: "Chef Meera Devi",
    chefImage: "https://images.unsplash.com/photo-1607631568010-a87245c0daf8?w=300&q=85",
  },
  {
    id: "skyfire",
    name: "Skyfire Rooftop",
    cuisine: "Pan-Asian · Rooftop",
    description: "Perched 12 floors above the city, Skyfire offers breathtaking panoramic views paired with innovative Pan-Asian cuisine and the finest Japanese whisky collection in India.",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=85",
    hours: "6:30 PM – 12:00 AM",
    location: "12th Floor, Rooftop",
    priceRange: "₹6,500 per person",
    tag: "Rooftop Experience",
    chef: "Chef Kenji Tanaka",
    chefImage: "https://images.unsplash.com/photo-1583394293214-0b3b9e5a4b4a?w=300&q=85",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "Priya & Arjun Mehta",
    role: "Destination Wedding Guests",
    location: "Mumbai, India",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=85",
    rating: 5,
    text: "The Aurum Palace didn't just host our wedding — it became the most magical chapter of our love story. Every detail was perfection. The palace courtyard at sunset, the floral arrangements, the cuisine — we still dream about it.",
    stay: "Royal Wedding Package · 5 Nights",
  },
  {
    name: "James Whitfield",
    role: "CEO, Whitfield Capital",
    location: "London, UK",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=85",
    rating: 5,
    text: "I have stayed at the finest hotels across six continents. The Aurum Palace stands alone. The Presidential Suite is a masterpiece of design, the butler service is telepathic, and the Golden Ember restaurant is worth the flight alone.",
    stay: "Presidential Suite · 7 Nights",
  },
  {
    name: "Aisha Al-Rashid",
    role: "Fashion Designer",
    location: "Dubai, UAE",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=85",
    rating: 5,
    text: "As someone who lives and breathes aesthetics, The Aurum Palace is a revelation. Every corner is a photograph, every moment is a memory. The spa treatments left me feeling reborn. I return every year without fail.",
    stay: "Royal Maharaja Suite · 4 Nights",
  },
  {
    name: "Sophie Laurent",
    role: "Travel Writer, Condé Nast",
    location: "Paris, France",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=85",
    rating: 5,
    text: "In 20 years of luxury travel writing, I have never encountered a property that so perfectly balances heritage and modernity. The Aurum Palace is not just a hotel — it is a living, breathing work of art.",
    stay: "Sky Penthouse · 5 Nights",
  },
  {
    name: "Rajiv & Sunita Sharma",
    role: "25th Anniversary Celebration",
    location: "Delhi, India",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=85",
    rating: 5,
    text: "For our 25th anniversary, we wanted something extraordinary. The Aurum Palace exceeded every expectation. The private lake dinner, the heritage walk, the Ayurvedic spa — the most romantic experience of our lives.",
    stay: "Ocean Villa · 3 Nights",
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  { src: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=85", category: "Suites", title: "Presidential Suite", tall: true },
  { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=85", category: "Dining", title: "Golden Ember" },
  { src: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=85", category: "Hotels", title: "Infinity Pool" },
  { src: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=85", category: "Spa", title: "Wellness Sanctuary", tall: true },
  { src: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=85", category: "Weddings", title: "Palace Wedding" },
  { src: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=85", category: "Architecture", title: "Palace Facade" },
  { src: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=85", category: "Suites", title: "Royal Suite" },
  { src: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=85", category: "Hotels", title: "Ocean Villa Pool", tall: true },
  { src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=85", category: "Dining", title: "Maharaja Courtyard" },
  { src: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&q=85", category: "Spa", title: "Treatment Room" },
  { src: "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&q=85", category: "Weddings", title: "Grand Ballroom" },
  { src: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=85", category: "Architecture", title: "Heritage Corridor" },
];
